### ISSUE TITLE
No more new libraries?

### ISSUE THREAD

**Issue by lopspower** [cesards/AndroidElementals#16]
There are more new libraries?
Last update is 11 months ago :(

**Comment by cesards** [comment]
Hi @lopspower ! Sorry but I can't maintain this anymore :-( Check out all the libraries in Android Arsenal. Its much worth it ;-)

**Comment by cesards** [comment]
BTW there is very good stuff in your Github account. Congratz! I starred some of your libraries few months ago ;-)

**Comment by lopspower** [comment]
Thank you :) your github account is also impressive.
Android Elementals is a reference for me. It's a shame that you don't continue to maintain it. 
Android Arsenal is quite different. This is a massive list of libraries and not a list of the best like yours.

**Comment by cesards** [comment]
Yep, there are good libraries there, but I haven't updated it for a year and in a year there are a lot of changes!

I would recommend you this tool to keep tracking your favourite libraries:
app.astralapp.com

Highly recommended! I need to clean a bit the repo, I don't think it's a good thing having this README as one of the first libraries shown in the repo. I suppose you get me :-) :+1:
