### ISSUE TITLE
IconFont library for ionicon font

### ISSUE THREAD

**Issue by MarsVard** [cesards/AndroidElementals#8]
I made this some time ago becuase I use it myself  might come handy for other devs https://github.com/MarsVard/IonIconView

**Comment by cesards** [comment]
Hi @MarsVard ! As I told the rest, thank you for trying to collaborate, and if I were you I would add your library to android-arsenal.com . Much worth it! I already starred your library some time ago. Good job you too!! :+1: I'm gonna erase the repo in some weeks :-P
