### ISSUE TITLE
I want to recommend my libraries.

### ISSUE THREAD

**Issue by daimajia** [cesards/AndroidElementals#9]
https://github.com/daimajia/AnimationEasingFunctions

https://github.com/daimajia/AndroidViewHover

https://github.com/daimajia/AndroidImageSlider

**Comment by cesards** [comment]
Very very good stuff!!! Congratz! I think there is no point in maintain this repo anymore. I don't have much time to do it so.. It's much better adding your libraries to Android Arsenal! I already starred all of your libraries BTW! :-) Good job! :+1:
